### ISSUE TITLE
Missing acces-token in Response Header

### ISSUE THREAD

**Issue by p-engelkes** [lynndylanhurley/devise_token_auth#1053]
I'm having a problem that the access-token in my Response Header is sometimes empty. My application is pretty new and I started with authentication. For my Frontend I am using React and the redux-token-auth library. 

Registering and loggin in users works without a problem. After refreshing my page I send a request to validate my token. In the response I get the new _access-token_  which is stored in localStorage via redux-token-auth. Most of the time this process works like a charm but for some Requests the _access-token_ in the Response is empty (still getting SUCCESS - 200), which breaks redux-token-auth because an empty _access-token_ gets saved in localStorage.

Is this a problem with redux-token-auth and after a 200 I can just use the old _access-token_ or is this a bug that an empty _access-token_ is sent?

Versions:
- Ruby 2.3.3
- Rails 5.1.4
- Devise Token Auth 0.1.43.beta1
- Devise 4.3.0

Fronted:
- redux-token-auth

**Comment by zachfeldman** [comment]
Try turning off, "change_headers_on_each_request" . See the README

**Comment by KelseyDH** [comment]
Random question from the README docs on this:

> Note that when the server identifies that a request is part of a batch request, the user's auth token is not updated. The auth token will be updated and returned with the first request in the batch, *and the subsequent requests in the batch will not return a token.* This is necessary because the order of the responses cannot be guaranteed to the client, and we need to be sure that the client does not receive an outdated token after the the last valid token is returned.

Does the behaviour (of not returning an auth-token on batch requests) still occur if `config.change_headers_on_each_request` is set to `false`?  Or in those cases, will devise_token_auth always return an auth-token no matter how quickly it receives a batch of requests?

**Comment by lynndylanhurley** [comment]
>Or in those cases, will devise_token_auth always return an auth-token no matter how quickly it receives a batch of requests?

That should be correct. Are you seeing different behavior?

**Comment by KelseyDH** [comment]
@lynndylanhurley   No I just wanted to confirm as the documentation didn't clarify, and it definitely would have definitely been a gotcha for my API consumers.  Thanks for clarifying!

**Comment by p-engelkes** [comment]
> Try turning off, "change_headers_on_each_request" . See the README

Thanks 👍 That fixed it for me.

**Comment by MaicolBen** [comment]
Closing since I see that fixed for you

**Comment by lostan** [comment]
I believe the explanation for blank token are here:
[https://github.com/lynndylanhurley/devise_token_auth/blob/master/docs/conceptual.md]

> About batch requests
> Note that when the server identifies that a request is part of a batch request, the user's auth token is not updated. The auth token will be updated and returned with the first request in the batch, and the subsequent requests in the batch will not return a token. This is necessary because the order of the responses cannot be guaranteed to the client, and we need to be sure that the client does not receive an outdated token after the the last valid token is returned.

**Comment by Hamdan85** [comment]
Hey guys, even setting it to false I'm still getting the same issue... 
would you help?

Im using Rails5.2

**Comment by MaicolBen** [comment]
@Hamdan85 you have another issue like the user isn't logged correctly, can you tell me the which endpoint and what headers do you send?

**Comment by Hamdan85** [comment]
I didn't quite understand the question.. why you ask that? Because of the
scope? Because in my case the scope was defined by before_filter
:authebticate_admin being admin the scope and devise_scope in router file.

Em sáb, 19 de jan de 2019 21:16, Maicol Bentancor <notifications@github.com>
escreveu:

**Comment by MaicolBen** [comment]
@Hamdan85 Because it's pretty common seeing people reporting issues of undefined current user or missing headers, probably it's due to missing configuration or something related. I guess you mistyped "authebticate_admin" here and not in the code. So I guess also that you have current user set, you can debug the method `update_auth_header` in the controller. Do you have the lastest version of this gem?

**Comment by Hamdan85** [comment]
@MaicolBen i didnt do it becaus of an error... it's just because it wasnt supporting multi model users... 
the scope was fixed in :user 

This pull request is only making it adaptable to multi model user structure.

**Comment by vkononov** [comment]
Had the same issue. What I have noticed is that if devise_token_auth is not sending the token, it means the token hasn't changed since the last request. In other words, if the token is not present, use the one from the previous request. Works for both tokens that change on each request and those that don't.

**Comment by Alie-Ammaar** [comment]
also having same issue, token is created after user signup but not appended to header.

**Comment by Hamdan85** [comment]
Update your gem. Force update.
The last version is working ok.

Em sex, 14 de jun de 2019 09:58, Alie-Ammaar <notifications@github.com>
escreveu:

**Comment by hgky95** [comment]
I already applied "change_headers_on_each_request" and updated the gem but the problem still there.
However, I saw that, if I use the `create ` method from the `DeviseTokenAuth::SessionsController,` the problem will not occur.
It just occured when I tried to override `create ` method in my controller.
Anyone have idea about it?

**Comment by SabhariKarthik-rq** [comment]
Hi @hgky95 , I am facing the issue exactly as you. Could you please let me know how you resolved this issue?

**Comment by hgky95** [comment]
> Hi @hgky95 , I am facing the issue exactly as you. Could you please let me know how you resolved this issue?

Hi @SabhariKarthik-rq , As I remembered (not sure because I stopped it some months ago), I used the `create` default method from the `DeviseTokenAuth::SessionsController` and I don't override it. With the default method, it fixed with my business situation so I no need to custom anything.

**Comment by SabhariKarthik-rq** [comment]
Okay @hgky95 , Thanks. Anyone else who have solved this problem without going back to the default code?

**Comment by ziaulrehman40** [comment]
I am using redux-token-auth, and it does not handle missing token and just replaces with nil in localStorage, causing a logout(lost token).

I handled nil token in my requests, but seems like will have to do the same in external libs as well :/

**Comment by laurenmacam** [comment]
> I am using redux-token-auth, and it does not handle missing token and just replaces with nil in localStorage, causing a logout(lost token).
> 
> I handled nil token in my requests, but seems like will have to do the same in external libs as well :/

Same issue here, and i would like to use the feature to change tokens in each request, thats the main feature of this library.
@ziaulrehman40  Are you handling the token by setting the previous one when it comes null in the response? Are you doing it on front end or in Rails?

**Comment by ziaulrehman40** [comment]
Issue was with redux token auth, i have wrote some patching scripts in it and have commented them on respective issues in redux token auth, when i am back to my machine will try to find and link them here

**Comment by ziaulrehman40** [comment]
@laurenmacam 
Complete script i am using which fixes both https://github.com/kylecorbelli/redux-token-auth/issues/45 and https://github.com/kylecorbelli/redux-token-auth/issues/57 is following:

```
echo '----------------------'
echo 'Patching redix token auth due to https://github.com/kylecorbelli/redux-token-auth/issues/45 and https://github.com/kylecorbelli/redux-token-auth/issues/57'
echo 'It adds if checks of empty access-token and sets headers for sign-out request'
echo '----------------------'
echo 'UPDATE THIS SCRIPT!!!!! if redux-token-auth is not on version: 0.19.0'
echo '----------------------'

REPLACE="                        if (response.headers['access-token'] && response.headers['access-token'] !== '') auth_1.setAuthHeaders(response.headers);";
ESCAPED_REPLACE=$(printf '%s\n' "$REPLACE" | sed -e 's/[\/&]/\\&/g');
sed -i.buk "165s/.*/$ESCAPED_REPLACE/" node_modules/redux-token-auth/dist/actions.js

REPLACE2='                        if (response.headers["access-token"] && response.headers["access-token"] !== "") auth_1.persistAuthHeadersInLocalStorage(response.headers);';
ESCAPED_REPLACE2=$(printf '%s\n' "$REPLACE2" | sed -e 's/[\/&]/\\&/g');
sed -i.buk "167s/.*/$ESCAPED_REPLACE2/" node_modules/redux-token-auth/dist/actions.js

REPLACE3='                                data: userSignOutCredentials, headers: userSignOutCredentials,';
ESCAPED_REPLACE3=$(printf '%s\n' "$REPLACE3" | sed -e 's/[\/&]/\\&/g');
sed -i.buk "234s/.*/$ESCAPED_REPLACE3/" node_modules/redux-token-auth/dist/actions.js

rm node_modules/redux-token-auth/dist/actions.js.buk
```

And further instructions to use this patch can be found [here](https://github.com/kylecorbelli/redux-token-auth/issues/45#issuecomment-833664584).
Hope it helps

**Comment by sndyegoluz** [comment]
Try include this code:
```
config.middleware.insert_before 0, Rack::Cors do
      allow do
        origins '*'
        resource '*',
          :headers => :any,
          expose: ['access-token', 'expiry', 'token-type', 'uid', 'client'],
          :methods => [:get, :post, :path, :options, :put, :delete]
      end
    end
```
 ...on your config/application.rb file. Works fine for me.
